### ISSUE TITLE
Problem when performing segmentation with one class

### ISSUE THREAD

**Issue by Perenn1s** [sunjesse/shape-attentive-unet#1]
I am not sure if I do understand the code correctly. It seems that I have to claim at least 3 classes for segmentation task. I guess it is because model setting such as Jaccard?

**Comment by sunjesse** [comment]
Hi, to segment one class you'll have to comment out code in SegmentationModuleBase's pixel_acc function that calculates the Jaccard for the other classes! We are aware this could be better implemented so we will work on fixing it :) Thanks for pointing it out

**Comment by sunjesse** [comment]
The code has just been updated so that no code has to be manually adjusted when changing the number of classes. Only the num_class argument needs to be filled in.
