### ISSUE TITLE
data download 

### ISSUE THREAD

**Issue by olfa-koubaa** [sunjesse/shape-attentive-unet#2]
hello 
where can I find the AC17data to download ? 
thanks in advance

**Comment by sunjesse** [comment]
Hi,

The data can be found on this platform upon signing up: https://acdc.creatis.insa-lyon.fr/

Thanks for the interest in our work!

Jesse

**Comment by Asraraf** [comment]
This provided link is unable to connect : https://acdc.creatis.insa-lyon.fr/
kindly provide appropriate link to data
Thanks!
