### ISSUE TITLE
About the unused problem of the out variable of the DualAttBlock module

### ISSUE THREAD

**Issue by tongxiaozhong14** [sunjesse/shape-attentive-unet#3]
Thank you very much for your article, your article is very well written.
But while reading your github code, I have a question about the DualAttBlock module. In the code, you define
  out = torch.mul(spatial.expand_as(channel) + 1, channel) # F(X) = C(X)*(1+S(X))
         return fused, spatial,
There are related discussions in your paper, but out in the code is an unused variable. Can you help explain? ?
Thank you again for your work, and look forward to your answer to my questions as soon as possible.

**Comment by sunjesse** [comment]
Hi,

Thank you very much for reading our paper. We have just realized that this was a mistake in the GitHub version of our code; the last line should `return out, spatial` instead as done in our original version of our code. We have updated the file accordingly to fix this issue. Thank you for pointing this out!

Jesse
