### ISSUE TITLE
The size of the output image does not match the input image size

### ISSUE THREAD

**Issue by tongxiaozhong14** [sunjesse/shape-attentive-unet#4]
Dear author, thank you very much for sharing your code, but this problem occurred when I used your code to train the ISIC2017 dataset? ? ?
How can I solve it?
Q1:ValueError:Target size (torch.Size([1,1,383,511])) must be as input size ([torch.Size[1,1,384,512]])".format(target.size(),input.size()))
Look forward to your reply

**Comment by sunjesse** [comment]
Hi,

The heights and width of your input image and target image should both be a power of two due to the upsampling steps. I recommend padding and cropping to achieve this.

Thanks,
Jesse
