### ISSUE TITLE
would you please tell me how to use the model step by step?

### ISSUE THREAD

**Issue by jiangjiaxi96** [sunjesse/shape-attentive-unet#5]

**Comment by sunjesse** [comment]
Hi,

Thank you for your interest in our work. To run the code, you can follow the steps below:

1. Register on https://acdc.creatis.insa-lyon.fr/#challenges and download the ACDC - Segmentation dataset.
2. Assign the root directory of the dataset to the DATA_ROOT variable at the bottom of train.py. Alternatively, you can fill the flag -data-root to the root directory each time you run the code. 
3. Run train.py.

Please feel free to reach out if you have any further difficulties with running the code. Should you be interested in working with a different dataset, you can adapt our dataloader to your dataset and copy over the model folder to your workspace. We recommend adapting our dataloader as our model requires the binary edge contours as a ground truth, which is computed in our dataloader code. 

Best,
Jesse

**Comment by moegi161** [comment]
I tried to use your code with AC17 dataset but it shows errors like this:
`FileNotFoundError: No such file or no access: '../../dataset/AC17/training/training/train/img/patient089_frame01.nii'`
Do I need to split the dataset myself beforehand or are there any preprocessing code?
The AC17 training dataset I have downloaded from the provided link is grouped by patients. train/val and img/seg are not separated. 

Thanks

**Comment by sunjesse** [comment]
Hi,

You're right. I just modified the dataloader code so you can run it immediately after downloading the dataset without any extra preprocessing (such as separating masks and images as we originally did into different folders). Please pull the code and try running it again, in particular, files `ac17_dataloader.py` and `test_loader.py` were modified.

**Comment by Asraraf** [comment]
Hi,
The link provided here for data download is not working and raising the following error:
Your connection is not private

**Comment by sunjesse** [comment]
Hi, 

You can bypass that by clicking 'Advanced' and 'Go to site anyways'.
