### ISSUE TITLE
Can Shape attentive unet (SAUNet) be used for age estimation?

### ISSUE THREAD

**Issue by annieMicheal** [sunjesse/shape-attentive-unet#6]
I'm currently doing an age estimation project. Can I use Shape attentive unet (SAUNet) for estimating the age of a person. Thanks in advance.

**Comment by sunjesse** [comment]
Hi, thank you for your interest in our work!

SAUNet does not have a natural application for age estimation tasks as the structure of the model is designed for segmentation tasks. However, it is indeed possible to incorporate modules from this work in developing improved deep regression models that are more tailored for your task.

Best,
Jesse
