### ISSUE TITLE
input size and target size not match error

### ISSUE THREAD

**Issue by Asraraf** [sunjesse/shape-attentive-unet#8]
Hi,
The following error occurs while executing train.py on the AC17 dataset.
 
"raise ValueError(
ValueError: Using a target size (torch.Size([1, 256, 256])) that is different to the input size (torch.Size([1, 1, 256, 256])) is deprecated. Please ensure they have the same size."

Looking forward to your response.
Thanks!

**Comment by sunjesse** [comment]
Hi,

Thank you for raising this issue, I've updated the repo accordingly (in particular, `models.py` line 104 was edited) to fix this error. Please pull again, or you can copy over `models.py` and replace it in your repo.

**Comment by Asraraf** [comment]
Hi, 

Thanks for updating your code. The previous problem has been resolved by this update. However, the training goes well till the 1500th iteration of the 1st epoch and it raises the following error:       

 "ValueError(
ValueError: Expected input batch_size (1) to match target batch_size (256)."

shape-attentive-unet-master\models\models.py", line 104, in forward
    loss = self.crit((p[0], p[1]), (feed_dict['mask'][0].long(), feed_dict['mask'][1])) 

Looking forward to your response.

**Comment by Asraraf** [comment]
Hi,

The value error has been resolved by updating line 104 in model.py file.

        loss = self.crit((p[0], p[1]), (feed_dict['mask'][0].long().unsqueeze(0), feed_dict['mask'][1].unsqueeze(0)))

**Comment by sunjesse** [comment]
Hi,

Sorry for late response. Glad to hear you figured it out. I'll update the code accordingly to fix this error!
